  myo-demo.cpp
c:\users\hrlab-andi\myo\myo-sdk-win-0.9.0\include\myo\cxx\detail\throwonerror.hpp(39): warning C4297: 'myo::ThrowOnError::~ThrowOnError': function assumed not to throw an exception but does
  c:\users\hrlab-andi\myo\myo-sdk-win-0.9.0\include\myo\cxx\detail\throwonerror.hpp(39): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
c:\users\hrlab-andi\myo\myo-sdk-win-0.9.0\include\myo\cxx\detail\throwonerror.hpp(45): warning C4297: 'myo::ThrowOnError::~ThrowOnError': function assumed not to throw an exception but does
  c:\users\hrlab-andi\myo\myo-sdk-win-0.9.0\include\myo\cxx\detail\throwonerror.hpp(45): note: destructor or deallocator has a (possibly implicit) non-throwing exception specification
  myo-demo_fall2017.vcxproj -> C:\Users\hrlab-andi\myo\my-code\myo-demo_fall2017\x64\Debug\myo-demo_fall2017.exe
